export default color = { 
    Cian : '2BF0D7',
    White : 'FFFFFF',
    MainBlue : '67A4F7',
    Black : '202020',
    RedBottoms: 'D22525',
    GreenBottoms: '8CCF4D',
    YellowBottoms: 'DFC01D',
    BackgroundPatient: '67A4F7',
    SugarBlood: '',
    BloodPressure: '',
    Temperature: '',
    HearthRate: '',
    Oxigen: '',
    BreathingFrecuency: '',
};