const translations = {
    en: {
        welcome: "Welcome",
        welcome2: "Welcome to",
        start: "Start",
        login: "Login",
        email: "Email",
        emailPlaceH: "something@email.com",
        password: "Password",
        forgetPass: "Forget Password?",
        noAccount: "Don\'t have an account?",
        signup: "Sign Up",
        name: "Name",
        lastName: "Last name",
        minPass: "Minimum password-lenght 8 characters",
        confirmPass: "Confirm password",
        identPass: "Passwords must be identical",
        yesAccount: "Already have an account?",
        policy: "I\'ve already read the policy of",
        tAndC: "Terms and Conditions",
        dontWorry: "Don't worry! It occurs. Please enter the email address linked with your account.",
        passRecovery: "Password recovery",
        enterEmail: "Enter your email",
        sendCode: "Send Code",
        rememberPass: "Remembered password?",
        otp: "OTP Verification",
        enterCode: "Enter the verification code we just sent on your email address.",
        verify: "Verify",
        noCode: "Didn\'t received the code?",
        resend: "Resend",
        createPass: "Create new password",
        newPass: "Your new password must be unique from those previously used.",
        newPassPH: "Enter new Password",
        resetPass: "Reset password",
        passChange: "Password Changed!",
        passSuccess: "Your password has been changed successfully.",
        back2Login: "Back To Login",
        quitting: "Quitting",
        ruSure: "Are you sure?",
        txtTandC: "Welcome to SACIE. Before using this application, we ask you to carefully read the following terms and conditions. By accessing and using this application, you agree to comply with the terms and conditions set forth below. If you do not agree to these terms, we recommend that you do not use the application.\nBy accessing and using the application, I agree to abide by the terms set forth. SACIE is an application specifically designed to capture information in the nursing field and provide support to healthcare professionals such as myself. I recognize the importance of using the application in a lawful manner and complying with all applicable laws and regulations. I further understand that my privacy is valuable and will be respected in accordance with the SACIE Privacy Policy.\nI acknowledge that all intellectual property rights related to the application belong to SACIE or third parties. I am not granted any right to use trademarks or copyrighted content without proper authorization.\nI understand that SACIE provides the application \"as is\", without guaranteeing its availability or suitability. Furthermore, I am aware that SACIE is not liable for any damages arising from the use of the application.\nSACIE reserves the right to modify or terminate the application at any time. These terms and conditions are governed by the laws of Mexico, and any dispute that may arise shall be subject to the exclusive jurisdiction of the Mexican courts.\nI further understand that the data I provide through the application may be stored and processed on servers located abroad, in accordance with applicable data protection laws and regulations.",
        agree: "I agree with terms and conditions",
        continue: "Continue",
        age: "Age",
        bed: "Bed",
        newPatient: "New Patient",
        newMed: "New Medicine",
        newTest: "New Test",
        howRegister: "How would you like to register it?",
        scan: "Scan",
        manually: "Manually",
        patients: "Patients",
        account: "Account",
        noti: "Notification",
        language: "Language",
        logout: "Logout",
        darkMode: "Dark Mode",
        profile: "Profile",
        editProfile: "Edit profile",
        fullName: "Full name",
        phone: "Phone number",
        eng: "English (North America)",
        spa: "Spanish (Mexico)",
        notis: "Notifications",
        info: "Information",
        temperature: "Temperature",
        pressure: "Pressure",
        bloodTypeSpace: "Blood\ntype",
        glucose: "Glucose",
        mo: "Mo",
        tu: "Tu",
        we: "We",
        th: "Th",
        fr: "Fr",
        sa: "Sa",
        su: "Su",
        printQr: "Print QR",
        printFull: "Print full patient\ninformation",
        med: "Medicine",
        moreMed: "More medicine",
        addMed: "Add\nmedicine",
        medName: "Medicine name",
        medNamePH: "Penicillin",
        dosage: "Dosage",
        intervals: "Intervals of",
        via: "Via",
        add: "Add",
        editMed: "Modify\nmedicine",
        update: "Update",
        notes: "Notes",
        medicalTest: "Medical Test",
        addTest: "Add Test",
        doneBy: "Done by",
        date: "Date",
        pickDatePH: "Pick a date",
        downloadFull: "Download full\nMedical test",
        setDocument: "Set Document",
        vitalSigns: "Vital Signs",
        heartRate: "Heart Rate",
        breFrequency: "Breathing\nFrequency",
        oxygen: "Oxygenation",
        healtCondSpace: "Healt\nCondition",
        time: "Time",
        value: "Value",
        setAlarmInt: "Set Alarm In Intervals Of:",
        rUSureData: "Are you sure about the data?",
        register: "Register",
        gender: "Gender",
        healtCond: "Healt condition",
        birthday: "Date of Birth",
        next: "Next",
        maritalStatus: "Marital Status",
        checkIn: "Check-in time",
        daysStay: "Days of Stay",
        service: "Service",
        bloodType: "Blood type",
        incomeOr: "Income Orientation",
        medRecNum: "Medical Record Number",
        medDiag: "Medical Diagnostic",
        errorMsg: "Must be at least 3 characters.",
        patiName: "Patient's name",
        docName: "Doctor's name",
        camPermission:"Requesting camera permission...",
        noPermission:"No permission has been granted for camera",
        scanned: "Scanned",
        //Screen name
        SplashScreen: "Splash",
        LoginScreen: "Login",
        SignUpScreen: "Sign Up",
        ForgotPasswordScreen: "Forgot password",
        OTPVerificationScreen: "OTP verification",
        ResetPasswordScreen: "Reset password",
        PasswordChangedScreen: "Password changed",
        ExitScreen: "Exit",
        TermnsAndConditionsCheckBoxScreen: "Terms & Conditions",
        TermnsAndConditionsTxtScreen: "Terms & Conditions.",
        PrincipalScreen: "Principal",
        QRScanScreen: "QR Scan",
        MenuScreen: "Menu",
        AccountScreen: "Account",
        LanguageScreen: "Language",
        NotificationScreen: "Notificactions",
        EditAccountScreen: "Edit account",
        DetailsScreen: "Details",
        MedicineScreen: "Medicine",
        RegisterMedicineScreen: "Register medicine",
        UpdateMedicineScreen: "Update medicine",
        RegisterMedicineNPScreen: "Register medicine NP",
        NotesScreen: "Notes",
        MedicalTestScreen: "Medical Test",
        RegisterMedicalTest: 'Register medical test',
        RegisterMedicalTest2: 'Register medical test pt2',
        RegisterMedicalTestNP: 'Register medical test NP',
        VitalSignsScreen: "Vital signs",
        BloodPressureScreen: "Blood pressure",
        HeartRateScreen: "Heart rate",
        SugarBloodScreen: "Sugar blood",
        TemperatureScreen: "Temperature",
        BreathingFrequencyScreen: "Brething frequency",
        OxigenScreen: "Oxygenation",
        HealthConditionScreen: "Health condition",
        ManualRegisterPt1Screen: "Manual register pt1",
        ManualRegisterPt2Screen: "Manual register pt2",
        ManualRegisterPt3Screen: "Manual register pt3",
        QRScanScreen: "QR Scanner",
    },
    esp: {
        welcome: "Bienvenido",
        welcome2: "Bienvenido a",
        start: "Comenzar",
        login: "Iniciar de sesión",
        email: "Correo",
        emailPlaceH: "algo@email.com",
        password: "Contraseña",
        forgetPass: "¿Olvidaste tu contraseña?",
        noAccount: "¿No tienes una cuenta?",
        signup: "Registrarse",
        name: "Nombre",
        lastName: "Apellido(s)",
        minPass: "Longitud mínima de 8 caracteres",
        confirmPass: "Confirmar contraseña",
        identPass: "Las contraseñas deben ser iguales",
        yesAccount: "¿Ya tienes una cuenta?",
        policy: "Ya he leído la política de",
        tAndC: "Términos y Condiciones",
        dontWorry: "¡No te preocupes! Suele suceder. Ingresa la dirección de correo electrónico vinculada a tu cuenta.",
        passRecovery: "Recuperación de contraseña",
        enterEmail: "Ingresa tu correo electrónico",
        sendCode: "Enviar código",
        rememberPass: "¿Recordaste tu contraseña?",
        otp: "Verificación OTP",
        enterCode: "Ingrese el código de verificación que acabamos de enviar a su dirección de correo electrónico.",
        verify: "Verificar",
        noCode: "¿No recibiste ningún código?",
        resend: "Reenviar",
        createPass: "Crear nueva contraseña",
        newPass: "Su nueva contraseña debe ser diferente a la usada anteriormente.",
        newPassPH: "Nueva contraseña",
        resetPass: "Restablecer contraseña",
        passChange: "¡Contraseña cambiada!",
        passSuccess: "Tu contraseña ha sido cambiada exitosamente.",
        back2Login: "Regresar para iniciar sesión",
        quitting: "Saliendo",
        rUSure: "¿Estas seguro?",
        txtTandC: "Bienvenida/o a SACIE. Antes de utilizar esta aplicación, te solicitamos que leas detenidamente los siguientes términos y condiciones. Al acceder y utilizar esta aplicación, aceptas cumplir con los términos y condiciones establecidos a continuación. Si no estás de acuerdo con estos términos, te recomendamos que no utilices la aplicación.\nAl acceder y utilizar la aplicación, acepto cumplir con los términos establecidos. SACIE es una aplicación diseñada específicamente para capturar información en el campo de enfermería y brindar apoyo a los profesionales de la salud como yo. Reconozco la importancia de utilizar la aplicación de manera legal y cumplir con todas las leyes y regulaciones aplicables. Además, entiendo que mi privacidad es valiosa y se respetará de acuerdo con la Política de Privacidad de SACIE.\nReconozco que todos los derechos de propiedad intelectual relacionados con la aplicación pertenecen a SACIE o a terceros. No se me concede ningún derecho para utilizar marcas registradas o contenido protegido por derechos de autor sin la debida autorización.\nEntiendo que SACIE proporciona la aplicación \"tal cual\", sin garantizar su disponibilidad o idoneidad. Además, soy consciente de que SACIE no se hace responsable de los posibles daños derivados del uso de la aplicación.\nSACIE se reserva el derecho de modificar o terminar la aplicación en cualquier momento. Estos términos y condiciones se rigen por las leyes de México, y cualquier disputa que pueda surgir estará sujeta a la jurisdicción exclusiva de los tribunales mexicanos.\nAdemás, comprendo que los datos que proporciono a través de la aplicación pueden ser almacenados y procesados en servidores ubicados en el extranjero, de acuerdo con las leyes y regulaciones aplicables en materia de protección de datos.",
        age: "Edad",
        bed: "Cama",
        newPatient: "Nuevo Paciente",
        newMed: "Medicina nueva",
        newTest: "Nueva prueba",
        howRegister: "¿Cómo te gustaría registrarlo?",
        scan: "Escanear",
        manually: "Manualmente",
        patients: "Pacientes",
        account: "Cuenta",
        noti: "Notificaciones",
        language: "Idiomas",
        logout: "Salir",
        darkMode: "Modo oscuro",
        profile: "Perfil",
        editProfile: "Editar perfil",
        fullName: "Nombre completo",
        phone: "Teléfono",
        eng: "Inglés (Americano)",
        spa: "Español (México)",
        notis: "Notificaciones",
        info: "Información",
        temperature: "Temperatura",
        pressure: "Presión",
        bloodTypeSpace: "Tipo de\nSangre",
        glucose: "Glucosa",
        mo: "Lu",
        tu: "Ma",
        we: "Mi",
        th: "Ju",
        fr: "Vi",
        sa: "Sa",
        su: "Do",
        printQr: "Imprimir QR",
        printFull: "Impimir información\ncompleta",
        med: "Medicamentos",
        moreMed: "Agregar medicina",
        addMed: "Agregar\nmedicina",
        medName: "Nombre de la medicina",
        medNamePH: "Penicilina",
        dosage: "Dosis",
        intervals: "Intervalos de",
        via: "Vía",
        add: "Agregar",
        editMed: "Modificar\nmedicamentos",
        update: "Actualizar",
        notes: "Notas",
        medicalTest: "Test médico",
        addTest: "Agregar test",
        doneBy: "Hecho por",
        date: "Fecha",
        pickDatePH: "Elige una fecha",
        downloadFull: "Descargar test\nmédico completo",
        setDocument: "Agregar documento",
        vitalSigns: "Signos Vitales",
        heartRate: "Ritmo cardíaco",
        breFrequency: "Frecuencia\nrespiratoria",
        oxygen: "Oxigenación",
        healtCondSpace: "Condición de\nSalud",
        time: "Tiempo",
        value: "Valor",
        setAlarmInt: "Programar alarma en intervalos de:",
        rUSureData: "¿Está seguro de los datos?",
        register: "Registar",
        gender: "Género",
        healtCond: "Condición de salud",
        birthday: "Fecha de nacimiento",
        next: "Siguiente",
        maritalStatus: "Estado civil",
        checkIn: "Hora de entrada",
        daysStay: "Días de estancia",
        service: "Servicio",
        bloodType: "Tipo de sangre",
        incomeOr: "¿El paciente ingresó consciente?",
        medRecNum: "Número de historial médico",
        medDiag: "Diagnóstico médico",
        errorMsg: "Debe tener al menos 3 carácteres.",
        patiName: "Nombre del paciente",
        docName: "Nombre del doctor",
        camPermission:"Solicitando permiso de cámara...",
        noPermission:"No se ha otorgado permiso para la cámara",
        scanned: "Escaneado",
        //Screen name
        SplashScreen: "Splash",
        LoginScreen: "Inicio de sesión",
        SignUpScreen: "Registrarse",
        ForgotPasswordScreen: "Olvidé mi contraseña",
        OTPVerificationScreen: "Verificación OTP",
        ResetPasswordScreen: "Restablecer contraseña",
        PasswordChangedScreen: "Contraseña modificada",
        ExitScreen: "Salir",
        TermnsAndConditionsCheckBoxScreen: "Terminos y Condiciones",
        TermnsAndConditionsTxtScreen: "Terminos y Condiciones.",
        PrincipalScreen: "Inicio",
        QRScanScreen: "Escaner QR",
        MenuScreen: "Menú",
        AccountScreen: "Perfil",
        LanguageScreen: "Idioma",
        NotificationScreen: "Notificaciones",
        EditAccountScreen: "Editar perfil",
        DetailsScreen: "Detalles",
        MedicineScreen: "Medicina",
        RegisterMedicineScreen: "Registrar medicamento",
        UpdateMedicineScreen: "Actualizar medicamento",
        RegisterMedicineNPScreen: "Registrar medicamento NP",
        NotesScreen: "Notas",
        MedicalTestScreen: "Test médico",
        RegisterMedicalTest: 'Registro de test médico',
        RegisterMedicalTest2: 'Registro de test médico pt2',
        RegisterMedicalTestNP: 'Registro de test médico NP',
        VitalSignsScreen: "Signos Vitales",
        BloodPressureScreen: "Presión arterial",
        HeartRateScreen: "Ritmo cardíaco",
        SugarBloodScreen: "Glucosa",
        TemperatureScreen: "Temperatura",
        BreathingFrequencyScreen: "Frecuencia respiratoria",
        OxigenScreen: "Oxigenación",
        HealthConditionScreen: "Estado de salud",
        ManualRegisterPt1Screen: "Registro manual pt1",
        ManualRegisterPt2Screen: "Registro manual pt2",
        ManualRegisterPt3Screen: "Registro manual pt3",
        QRScanScreen: "Escaner QR",
    }
};


export { translations };
